### ISSUE TITLE
Support for AsyncCountdownEvent

### ISSUE THREAD

**Issue by niemyjski** [StephenCleary/AsyncEx.Coordination#4]
I'm blocked until this is supported :\ Is there anything I can do to help out with this.

**Comment by StephenCleary** [comment]
Interesting. This is one of the more rarely-used types, and I was originally planning to drop it.

I can certainly add it back in, but part of this transition is a review of the semantics of all synchronization primitives. In the case of `AsyncCountdownEvent`, it was never a perfect match to `CountdownEvent` because it does not support reuse ("resetting").

So, first question: as a consumer, is a single-use `AsyncCountdownEvent` sufficient, or do you need a reusable `AsyncCountdownEvent`?

**Comment by niemyjski** [comment]
We are using it as single use in our unit tests and also had some extensions for it: https://github.com/exceptionless/Foundatio/search?utf8=%E2%9C%93&q=AsyncCountdownEvent+

**Comment by StephenCleary** [comment]
Added `AsyncCountdownEvent`, available in `1.0.0-delta-2`. The semantics are slightly different than the old AsyncEx version, but I think they actually make *more* sense this way. For your use case, it should work fine.

**Comment by niemyjski** [comment]
Thank you!!!
